# Generated by Django 5.2.6 on 2025-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmanager', '0002_alter_pdfdocument_options_pdfdocument_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
