# Generated by Django 5.2.6 on 2025-09-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmanager', '0003_alter_pdfdocument_created_at_and_more'),
    ]

    operations = [
    ]
